USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON DATABASE FOOTBALL_DB TO ROLE SYSADMIN COPY CURRENT GRANTS;

CREATE RESOURCE MONITOR IF NOT EXISTS football_monitor
WITH CREDIT_QUOTA = 50
     FREQUENCY = MONTHLY
     START_TIMESTAMP = IMMEDIATELY
TRIGGERS ON 50 PERCENT DO NOTIFY
         ON 80 PERCENT DO NOTIFY
         ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = football_monitor;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;


-- =======================================================================================
-- Objects 
-- =======================================================================================
USE ROLE SYSADMIN;
USE DATABASE FOOTBALL_DB;

-- schemas                                                                                        
CREATE SCHEMA IF NOT EXISTS FOOTBALL_DB.BRONZE;

-- tables                                
CREATE OR REPLACE TABLE FOOTBALL_DB.BRONZE.MATCHES_RAW (
    DATA VARIANT,
    COMPETITION VARCHAR,
    BATCH_ID VARCHAR,
    LOADED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE FOOTBALL_DB.BRONZE.TEAMS_RAW (
    DATA VARIANT,
    COMPETITION VARCHAR,
    BATCH_ID VARCHAR,
    LOADED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE FOOTBALL_DB.BRONZE.ODDS_RAW (
    DATA VARIANT,
    SPORT VARCHAR,
    EVENT_DATE DATE,
    BATCH_ID VARCHAR,
    LOADED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FOOTBALL_DB.BRONZE.USER_LOGINS (
    IP_ADDRESS STRING,
    LOGIN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE FILE FORMAT FOOTBALL_DB.BRONZE.JSON_FORMAT
TYPE = JSON;